# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3296b78ef017f40c42c3f0a3ff78a1b743cec9f5d7893d41dc553227ccd6e1e95ea7af55f4a96568d5d0e1c684922fbe850079ea5976d40a9dd80f9fd0d72a8a

test:
  secret_key_base: f9625291553787803b5b02c3a834e9bb8893dcd1d6991e77f9e537ba40139db78f1bb6c17f05bf339a3e01a19525f24c7eb42679d88ff407e33430fda54ceb73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
